spring:
  application:
    name: LoL-Chat
  datasource:
    url: jdbc:h2:mem:lolchat
    driver-class-name: org.h2.Driver
    username: sa
    password: ''
  h2:
    console:
      enabled: true
server:
  port: 8015

generative-ai:
  provider: ${GENERATIVE_AI_PROVIDER:OPENAI}

openai:
  base-url: https://api.openai.com
  api-key: ${OPENAI_API_KEY}

gemini:
  base-url: https://generativelanguage.googleapis.com
  api-key: ${GEMINI_API_KEY}