spring:
  application:
    name: LoL-Chat
  datasource:
    url: jdbc:h2:mem:lolchat
    driver-class-name: org.h2.Driver
    username: sa
    password: ''
  h2:
    console:
      enabled: true
server:
  port: 8015